import fs from 'node:fs';
const root=new URL('../',import.meta.url);
const diagnosticTest=process.env.DIAGNOSTIC_TEST==='1';
if(diagnosticTest)globalThis.location={search:'?diagnostic=1'};

const saved=new Map();globalThis.localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};const context=new Proxy({},{get:(t,k)=>t[k]??(()=>{})});const elements=new Map();function el(){return {style:{},classList:{add(){}},setAttribute(){},append(){},before(){},appendChild(){},setPointerCapture(){},getContext(){return context},firstElementChild:{},lastElementChild:{},getBoundingClientRect(){return {left:0,top:0,width:130,height:130}}}};globalThis.document={getElementById(id){if(!elements.has(id))elements.set(id,el());return elements.get(id)},createElement(){return el()},addEventListener(){}};document.head=el();document.body=el();globalThis.innerWidth=1200;globalThis.innerHeight=800;globalThis.devicePixelRatio=1;globalThis.addEventListener=()=>{};globalThis.requestAnimationFrame=()=>{};
let code=fs.readFileSync(new URL('dist/game.js',root),'utf8').replace("'./navigation.js?v=mobile-1'",JSON.stringify(new URL('dist/navigation.js',root).href)).replace("'./diagnostic.js?v=3'",JSON.stringify(new URL('dist/diagnostic.js',root).href)).replace("'./three.module.js'",JSON.stringify(new URL('dist/three.module.js',root).href)).replace("'./character.js'",JSON.stringify(new URL('dist/character.js',root).href)).replace("'./drive-controls.js'",JSON.stringify(new URL('dist/drive-controls.js',root).href)).replace("new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'})","({setPixelRatio(){},setSize(){},shadowMap:{},domElement:{},render(){}})");
code+=`\nfunction assert(v,m){if(!v)throw Error(m)};function advance(){for(let i=0;i<100;i++)updateMissions(.04)};started=true;pos.set(2,0,-6);ride();updateMissions(.016);assert(stage===1,'board completion');advance();props.slice(0,3).forEach(shatter);updateMissions(.016);assert(stage===2,'break completion');advance();escapeWins++;updateMissions(.016);assert(stage===3,'escape completion');advance();for(let t of currentMission().points){pos.set(t[0],0,t[1]);vehicleNow=null;for(let i=0;i<20;i++)updateMissions(.04);assert(!$('arrival').hidden&&$('arrivalprogress').value>.79,'delivery progress visible while stopped');for(let i=0;i<30;i++)updateMissions(.04)}assert(stage===4,'delivery completion');advance();vehicleNow=scooter;for(let t of currentMission().points){pos.set(t[0],0,t[1]);updateMissions(.016)}assert(stage===5,'race completion');advance();heat=30;updateMissions(.016);escapeWins++;updateMissions(.016);assert(stage===6,'chaos completion');advance();heat=0;vehicleNow=null;pos.set(9.5,0,-3);updateMissions(.016);assert(stage===7,'home completion');advance();vehicleNow=scooter;missionActive=false;const frozen=missionClock;updateMissions(2);assert(missionClock===frozen,'free roam timer frozen');missionActive=true;missionClock=.01;updateMissions(.04);assert(missionDelay>0,'race timeout retry');advance();hp=0;update(.016);assert(hp>0,'respawn');for(let i=0;i<600;i++)update(1/60);assert(Number.isFinite(pos.x),'finite simulation');saveProgress();assert(JSON.parse(localStorage.getItem('granny-chaos-progress-v2')).stage===7,'saved progression');stage=0;initMissions();assert(stage===7,'restore progression');for(let g of scene.children){if(g.isMesh&&g.geometry.attributes.position)assert(g.geometry.attributes.position.array.every(Number.isFinite),'finite mesh vertices')}let mesh=0;scene.traverse(o=>{if(o.isMesh)mesh++});console.log('PASS: all seven missions, recurring challenge, free-roam timer, timeout retry, respawn, 10-second simulation. Scene meshes:',mesh);`;
if(diagnosticTest){code=code.replaceAll("localStorage.getItem('granny-chaos-progress-v2')","localStorage.getItem('granny-chaos-diagnostic-progress')");code+='\nframe(performance.now()+16);console.log("PASS: diagnostic frame and telemetry with mocked Canvas context");';}
await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
